"""Public API for the Excel data toolbox core engine."""

# Pytest may import the repository root ``__init__.py`` as a stand-alone
# module when a checkout directory contains hyphens (for example the default
# GitHub Actions checkout).  Give relative imports their canonical package
# context in that narrow case; normal installed imports already set this
# value and are unaffected.
if not __package__:
    __package__ = "excel_data_toolbox"

from .analytics import (
    CategoryContributionResult,
    DataQualityReport,
    OutlierDetectionResult,
    QualityIssue,
    RFMAnalysisResult,
    TableComparisonResult,
    TrendAnalysisResult,
    aggregate_trend,
    assess_data_quality,
    category_contribution,
    compare_tables,
    correlation_matrix,
    cross_pivot,
    descriptive_statistics,
    detect_outliers,
    rfm_segmentation,
)
from .core import (
    concat_tables,
    export_tables,
    group_summary,
    join_tables,
    load_tables,
    lookup_match,
    mask_columns,
    profile_dataframe,
    select_rename_sort,
    smart_clean,
    split_dataframe,
)
from .fuzzy import (
    apply_value_mapping,
    cluster_similar_values,
    fuzzy_lookup,
    normalize_text,
)
from .finance import FINANCE_TASKS, FinanceAnalysisResult, analyze_finance
from .models import (
    CleaningConfig,
    CleaningReport,
    ColumnProfile,
    DataFrameProfile,
    ExportResult,
    OperationLog,
    OperationRecord,
)
from .recipes import (
    DataFrameFingerprint,
    ProcessingRecipe,
    RecipeRunReport,
    RecipeStep,
    RecipeStepReport,
    fingerprint_dataframe,
    run_recipe,
)
from .validation import (
    RuleValidationResult,
    ValidationReport,
    ValidationRule,
    validate_dataframe,
)
from .reconciliation import ReconciliationResult, reconcile_tables
from .delivery_qa import DeliveryAcceptance, verify_delivery, write_acceptance_json
from .large_data import dataframe_query, duckdb_available, query_files
from .order_intake import OrderQuote, quote_order
from .secure_secrets import SecureSecretStore
from .task_store import TaskRepository
from .workbook_fidelity import preserve_workbook_export, workbook_feature_inventory
from .advanced_automation import (
    build_vba_bundle,
    document_capabilities,
    extract_image_text,
    extract_pdf_tables,
    query_sqlite_read_only,
)
from .adaptive_report import (
    AdaptiveReportResult,
    build_adaptive_analysis_report,
    can_build_adaptive_report,
    infer_column_roles,
)
from .nl_agent import (
    ALLOWED_AGENT_OPERATIONS,
    SUPPORTED_DEEPSEEK_MODELS,
    AgentExecutionError,
    AgentExecutionResult,
    AgentPlan,
    AgentStep,
    DeepSeekAPIError,
    DeepSeekClient,
    NaturalLanguageAgent,
    PlanPreview,
    PlanValidationError,
    UnsupportedPlanError,
    build_table_catalog,
    execute_plan,
    preview_plan,
    validate_plan,
)

__all__ = [
    "CategoryContributionResult",
    "ALLOWED_AGENT_OPERATIONS",
    "SUPPORTED_DEEPSEEK_MODELS",
    "AgentExecutionError",
    "AgentExecutionResult",
    "AgentPlan",
    "AgentStep",
    "AdaptiveReportResult",
    "CleaningConfig",
    "CleaningReport",
    "ColumnProfile",
    "DataQualityReport",
    "DataFrameProfile",
    "DataFrameFingerprint",
    "DeepSeekAPIError",
    "DeepSeekClient",
    "DeliveryAcceptance",
    "ExportResult",
    "FINANCE_TASKS",
    "FinanceAnalysisResult",
    "OperationLog",
    "OperationRecord",
    "NaturalLanguageAgent",
    "OrderQuote",
    "OutlierDetectionResult",
    "PlanPreview",
    "PlanValidationError",
    "QualityIssue",
    "ProcessingRecipe",
    "RFMAnalysisResult",
    "RecipeRunReport",
    "RecipeStep",
    "RecipeStepReport",
    "RuleValidationResult",
    "ReconciliationResult",
    "SecureSecretStore",
    "TableComparisonResult",
    "TaskRepository",
    "TrendAnalysisResult",
    "UnsupportedPlanError",
    "ValidationReport",
    "ValidationRule",
    "aggregate_trend",
    "analyze_finance",
    "apply_value_mapping",
    "assess_data_quality",
    "build_vba_bundle",
    "build_adaptive_analysis_report",
    "build_table_catalog",
    "category_contribution",
    "can_build_adaptive_report",
    "cluster_similar_values",
    "compare_tables",
    "concat_tables",
    "correlation_matrix",
    "cross_pivot",
    "descriptive_statistics",
    "document_capabilities",
    "duckdb_available",
    "detect_outliers",
    "export_tables",
    "execute_plan",
    "extract_image_text",
    "extract_pdf_tables",
    "fuzzy_lookup",
    "fingerprint_dataframe",
    "group_summary",
    "join_tables",
    "infer_column_roles",
    "load_tables",
    "lookup_match",
    "mask_columns",
    "normalize_text",
    "profile_dataframe",
    "preview_plan",
    "preserve_workbook_export",
    "query_files",
    "query_sqlite_read_only",
    "quote_order",
    "reconcile_tables",
    "rfm_segmentation",
    "run_recipe",
    "select_rename_sort",
    "smart_clean",
    "split_dataframe",
    "validate_dataframe",
    "validate_plan",
    "verify_delivery",
    "workbook_feature_inventory",
    "write_acceptance_json",
    "dataframe_query",
]
